version: "3"
networks:
  laravel:
services:

  currikiprod-nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    container_name: currikiprod-nginx
    volumes:
      - ./data/nginx/prod-conf:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/nginx/log:/var/log/nginx
    ports:
      - ${FRONT_MAIN_PORT}:80
      - 443:443
    depends_on:
      - currikiprod-client
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - currikiprod-laravel  

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - currikiprod-laravel

    
  currikiprod-api:
    build:
      dockerfile: ./Dockerfile.api
      context: .
    container_name: currikiprod-api
    ports:
      - ${LARAVEL_API_LOCAL_PORT}:8000
      - 4003:4003
    volumes:
      - /var/www/html/vendor
      - ./api:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: always
    networks:
      - currikiprod-laravel

  currikiprod-admin:
    build:
      dockerfile: ./Dockerfile.admin
      context: .
    container_name: currikiprod-admin
    ports:
      - ${LARAVEL_ADMIN_LOCAL_PORT}:6000
    volumes:
      - /var/www/html/vendor
      - ./admin:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    restart: always
    networks:
      - currikiprod-laravel    

  currikiprod-client:
    build:
      dockerfile: ./Dockerfile.client
      context: .
    container_name: currikiprod-client
    volumes:
      - /app/build
      - /app/node_modules
      - ./client:/app
    restart: always
    networks:
      - currikiprod-laravel

  currikiprod-trax:
    build:
      dockerfile: ./Dockerfile.trax
      context: .
    container_name: currikiprod-trax
    ports:
      - 6900:6900
    volumes:
      - ./trax-lrs:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: always
    networks:
      - currikiprod-laravel

  currikiprod-tsugi:
    build:
      dockerfile: ./Dockerfile.tsugi
      context: .
    container_name: currikiprod-tsugi
    ports:
      - 6300:6300
    volumes:
      - ./tsugi:/var/www/html/tsugi
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: always
    networks:
      - currikiprod-laravel


networks:
  currikiprod-laravel:
    driver: bridge

