version: "3"
networks:
  laravel:
services:

  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    container_name: nginx
    ports:
      - 8082:80
    restart: always
    depends_on:
      - laravel-api
      - mysql
      - client
      - lti-provider
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${MYSQL_LOCAL_PORT}:3306
    volumes:
      - mysqldata:/var/lib/mysql
      - ./tmp/database/setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro
      - ./tmp/database/install_db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    # command: mysqld --init-file="/tmp/database/install_db.sql"
    networks:
      - laravel
  

  laravel-api:
    build:
      dockerfile: ./ActiveLearningStudio-laravel-api/Dockerfile.dev
      context: .
    container_name: laravel-api
    ports:
      - ${LARAVEL_API_LOCAL_PORT}:9000
    volumes:
      - ./ActiveLearningStudio-laravel-api:/var/www/html
    depends_on:
      - mongodb
    restart: always
    networks:
      - laravel

  lti-provider:
    build:
      dockerfile: ./ActiveLearningStudio-lti-provider/Dockerfile.dev
      context: .
    container_name: lti-provider
    ports:
      - ${LTI_PROVIDER_LOCAL_PORT}:9500
    volumes:
      - ./ActiveLearningStudio-lti-provider:/var/www/html
    depends_on:
      - mongodb
    restart: always
    networks:
      - laravel

      
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./ActiveLearningStudio-laravel-api:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - laravel-api
    networks:
      - laravel
      
  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./ActiveLearningStudio-laravel-api:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - laravel
      
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8088:80
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
      PMA_ABSOLUTE_URI: http://localhost:8082/phpmyadmin/
    networks:
      - laravel

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    working_dir: /var/app/current
    command: mongod
    ports:
      - "28018:27017"
    # environment:
    #   - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodbdata:/data/db
      - ./mongoscripts:/var/app/current/mongoscripts
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - laravel
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./ActiveLearningStudio-react-client
    container_name: client
    ports:
      - ${CLIENT_LOCAL_PORT}:3000
    volumes:
      - /var/app/current/node_modules
      - ./ActiveLearningStudio-react-client:/var/app/current
    restart: always
    networks:
      - laravel
volumes: #provide volume
  mongodbdata:
      external: true
  mysqldata:
      external: true

networks:
  laravel:
    driver: bridge