version: "3"
networks:
  laravel:
services:

  currikidev-goaccess:
    image: currikidev/goaccess:1.0.0
    container_name: currikidev-goaccess
    restart: always
    command: ["--no-global-config", "--config-file=/srv/config/goaccess.conf", "--log-file=/srv/logs/access.log"]

    ports:
      - 7890:7890
    networks:
      - currikidev-laravel

  # currikidev-goaccess-nginx:
  #   image: currikidev/goaccess-nginx:1.0.0
  #   container_name: currikidev-goaccess-nginx
  #   depends_on: 
  #     - currikidev-goaccess
  #   ports:
  #     - 7891:80
  #   networks:
  #     - currikidev-laravel

  currikidev-nginx:
    image: currikidev/nginx:1.0.0
    volumes:
      - ./data/nginx/log:/var/log/nginx
    container_name: currikidev-nginx
    ports:
      - ${FRONT_MAIN_PORT}:80
    restart: always
    depends_on:
      - currikidev-laravel-api
      - currikidev-mysql
      - currikidev-client
      - currikidev-lti-provider
    networks:
      - currikidev-laravel

  currikidev-mysql:
    image: currikidev/mysql:1.0.0
    container_name: currikidev-mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${MYSQL_LOCAL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    # command: mysqld --init-file="/tmp/database/install_db.sql"
    networks:
      - currikidev-laravel
  
  currikidev-auth-api:
    image: currikidev/auth-api:1.0.0
    container_name: currikidev-auth-api
    ports:
      - ${LARAVEL_AUTH_API_LOCAL_PORT}:8000
    depends_on:
      - currikidev-mongodb
    restart: always
    networks:
      - currikidev-laravel
    

  currikidev-laravel-api:
    image: currikidev/laravel-api:1.0.0
    container_name: currikidev-laravel-api
    ports:
      - ${LARAVEL_API_LOCAL_PORT}:9000
    depends_on:
      - currikidev-mongodb
    restart: always
    networks:
      - currikidev-laravel


  currikidev-h5p-api:
    image: currikidev/h5p-api:1.0.0
    container_name: currikidev-h5p-api
    ports:
      - ${LARAVEL_H5P_API_PORT}:7000
    depends_on:
      - currikidev-mysql
    restart: always
    networks:
      - currikidev-laravel
    

  currikidev-lti-provider:
    image: currikidev/lti-provider:1.0.0
    container_name: currikidev-lti-provider
    ports:
      - ${LTI_PROVIDER_LOCAL_PORT}:9500
    depends_on:
      - currikidev-mongodb
    restart: always
    networks:
      - currikidev-laravel
      
  currikidev-phpmyadmin:
    image: currikidev/phpmyadmin:1.0.0
    depends_on:
      - currikidev-mysql
    container_name: currikidev-phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_HOST: currikidev-mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
    networks:
      - currikidev-laravel

  currikidev-mongodb:
    image: currikidev/mongodb:1.0.0
    container_name: currikidev-mongodb
    restart: always
    working_dir: /var/app/current
    command: mongod
    ports:
      - "28018:27017"
    volumes:
      - currikidev-mongodbdata:/data/db
      - ./mongoscripts:/var/app/current/mongoscripts
    networks:
      - currikidev-laravel

  currikidev-client:
    image: currikidev/client:1.0.0
    container_name: currikidev-client
    ports:
      - ${CLIENT_LOCAL_PORT}:3000
    restart: always
    stdin_open: true
    networks:
      - currikidev-laravel

volumes: #provide volume
    currikidev-mongodbdata:
      external: true
    currikidev-mysqldata:
      external: true

networks:
  currikidev-laravel:
    driver: bridge
