FROM mysql:5.7.22

COPY currikidev-mysqldata/ /var/lib/mysql/
RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./tmp/database/setup.sql /docker-entrypoint-initdb.d/
COPY ./tmp/database/install_db.sql /docker-entrypoint-initdb.d/init.sql
COPY mysqlscripts /

# # Uncomment this to set up the database from a demo file:
# RUN mysqld --init-file="/tmp/database/install_db.sql"
