FROM node:8.9.3-alpine
WORKDIR /var/app/current
RUN ls /var/app/current
COPY ActiveLearningStudio-react-client/package*.json ./
RUN ls /var/app/current
COPY ActiveLearningStudio-react-client/package.json /var/app/current/
RUN npm install
COPY ActiveLearningStudio-react-client/ ./

RUN ls /var/app/current

COPY entrypoint.client.sh /var/app/current/
CMD ["/bin/sh", "/var/app/current/entrypoint.client.sh"]
# CMD ["npm", "run", "start:dev"]