apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.k8s.yml -o yamls/
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: currikidev-lti-provider
  name: currikidev-lti-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: currikidev-lti-provider
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.k8s.yml -o yamls/
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/currikidev-laravel: "true"
        io.kompose.service: currikidev-lti-provider
    spec:
      containers:
      - image: currikidev/lti-provider:1.0.0
        imagePullPolicy: IfNotPresent
        name: currikidev-lti-provider
        ports:
        - containerPort: 9500
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
